set(receipt "{}")
string(JSON receipt SET "${receipt}" compiler "\"${COMPILER}\"")
string(JSON receipt SET "${receipt}" compilerId "\"${COMPILER_ID}\"")
string(JSON receipt SET "${receipt}" compilerVersion "\"${COMPILER_VERSION}\"")
file(SHA256 "${COMPILER}" compiler_hash)
string(JSON receipt SET "${receipt}" compilerSha256 "\"${compiler_hash}\"")
string(JSON receipt SET "${receipt}" files "{}")
file(GLOB inputs "${TOOL_DIR}/*.cpp" "${TOOL_DIR}/*.h" "${TOOL_DIR}/*.cmake"
    "${TOOL_DIR}/CMakeLists.txt" "${TOOL_DIR}/.clangd")
list(APPEND inputs "${BUILD_DIR}/CMakeCache.txt" "${BUILD_DIR}/compile_commands.json" "${BINARY}")
foreach(path IN LISTS inputs)
    file(SHA256 "${path}" digest)
    string(JSON receipt SET "${receipt}" files "${path}" "\"${digest}\"")
endforeach()
file(WRITE "${BUILD_DIR}/build-identity.json" "${receipt}\n")
